name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven Test
        run: mvn --batch-mode --update-snapshots test
      - name: Build JavaDoc
        run: mvn --batch-mode javadoc:javadoc
      - name: Move JavaDoc
        run: mv target/site/apidocs public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public        
